name: "Deploy to Neocities"
on:
  push:
    branches:
      - main # run this job when I push to main
jobs:
  deploy:
    name: "Deploy to Neocities"
    runs-on: ubuntu-latest # the system the runner uses
    steps:
      - uses: actions/checkout@v4 # checkout the repo
      - uses: actions/setup-node@v3 # install node.js
        with:
          node-version: "23"
      - run: npm install
      - run: npx @11ty/eleventy
      - uses: bcomnes/deploy-to-neocities@v1 # deploy!
        with: # config for the action
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: "site/" # my build output directory
          cleanup: true # delete anything on neocities that's not in my dist_dir
          neocities_supporter: true
